const carsData = [
  {
    name: "Mercedes-Benz C220d Wagon",
    thumb: "c-class-wagon",
    price: 60,
    monthlyPrice: 1500,
    year: 2017,
    fuelConsumption: 5,
    fuel: "Diesel",
    large_bags: 4,
    number_doors: 5,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Mercedes-Benz C220d",
    thumb: "c-class",
    price: 50,
    monthlyPrice: 1200,
    year: 2013,
    fuelConsumption: 5,
    fuel: "Diesel",
    large_bags: 3,
    number_doors: 4,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Mercedes-Benz E220d",
    thumb: "e-class",
    price: 60,
    monthlyPrice: 1350,
    year: 2015,
    fuelConsumption: 5,
    fuel: "Diesel",
    large_bags: 3,
    number_doors: 4,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Mercedes-Benz E220d",
    thumb: "e-class",
    price: 50,
    monthlyPrice: 1100,
    year: 2013,
    fuelConsumption: 5,
    fuel: "Diesel",
    large_bags: 3,
    number_doors: 4,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Fiat 500",
    thumb: "fiat-500",
    price: 15,
    monthlyPrice: 450,
    year: 2011,
    fuelConsumption: 6,
    fuel: "Petrol",
    large_bags: 1,
    number_doors: 3,
    transmission: "Manual",
    number_seats: 5,
    extras: ["Bluetooth", "Panoramic sunroof"],
    available: true,
    photos: [],
  },
  {
    name: "Kia Soul",
    thumb: "kia-soul",
    price: 25,
    monthlyPrice: 650,
    year: 2013,
    fuelConsumption: 6,
    fuel: "Diesel",
    large_bags: 2,
    number_doors: 5,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Mercedes-Benz ML250",
    thumb: "mb-ml",
    price: 80,
    monthlyPrice: 2000,
    year: 2013,
    fuelConsumption: 7,
    fuel: "Diesel",
    large_bags: 5,
    number_doors: 5,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Mini Cooper",
    thumb: "mini-cooper",
    price: 40,
    monthlyPrice: 1000,
    year: 2018,
    fuelConsumption: 5,
    fuel: "Petrol",
    large_bags: 1,
    number_doors: 5,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: ["mini1.jpg", "mini2.jpg", "mini3.jpg"],
  },
  {
    name: "Nissan March",
    thumb: "nissan-march",
    price: 20,
    monthlyPrice: 500,
    year: 2015,
    fuelConsumption: 6.4,
    fuel: "Petrol",
    large_bags: 2,
    number_doors: 5,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Nissan Note",
    thumb: "nissan-note",
    price: 20,
    monthlyPrice: 550,
    year: 2017,
    fuelConsumption: 5,
    fuel: "Petrol",
    large_bags: 2,
    number_doors: 5,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Range Rover Evoque",
    thumb: "range-rover-evoque",
    price: 75,
    monthlyPrice: 2000,
    year: 2012,
    fuelConsumption: 8,
    fuel: "Diesel",
    large_bags: 3,
    number_doors: 5,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Volvo XC60",
    thumb: "volvo-xc60",
    price: 60,
    monthlyPrice: 1600,
    year: 2017,
    fuelConsumption: 5.5,
    fuel: "Diesel",
    large_bags: 3,
    number_doors: 5,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Renault Clio",
    thumb: "renault-clio",
    price: 40,
    monthlyPrice: 900,
    year: 2023,
    fuelConsumption: 5,
    fuel: "Petrol",
    large_bags: 1,
    number_doors: 2,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Renault Kadjar",
    thumb: "renault-kadjar",
    price: 50,
    monthlyPrice: 1200,
    year: 2023,
    fuelConsumption: 5,
    fuel: "Petrol",
    large_bags: 2,
    number_doors: 5,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Renault Arkana",
    thumb: "renault-arkana",
    price: 60,
    monthlyPrice: 1400,
    year: 2023,
    fuelConsumption: 5,
    fuel: "Petrol",
    large_bags: 2,
    number_doors: 5,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
  {
    name: "Renault Captur",
    thumb: "renault-captur",
    price: 45,
    monthlyPrice: 1100,
    year: 2023,
    fuelConsumption: 5,
    fuel: "Petrol",
    large_bags: 2,
    number_doors: 5,
    transmission: "Automatic",
    number_seats: 5,
    extras: [],
    available: true,
    photos: [],
  },
];

module.exports = carsData;
